server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Kumar-7868
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: 5e45c2dc6d1a8d41cf3a8f64d2d64a336d2c0ff12fbcf1d3c78091afc5319c6b
    expiration-ms: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE